language: scala
scala: 
  - 2.11.6
jdk:
  - oraclejdk8
env:
  - PLAY_VERSION=2.4.6
script:
  - "sbt ++$TRAVIS_SCALA_VERSION test"
  - "sbt ++$TRAVIS_SCALA_VERSION publish-local"

before_script:
  - wget http://downloads.typesafe.com/play/${PLAY_VERSION}/play-${PLAY_VERSION}.zip
  - unzip -q play-${PLAY_VERSION}.zip
script: play-${PLAY_VERSION}/play test

notifications:
  email: true