language: scala
scala: 
  - 2.11.6
jdk:
  - oraclejdk8
script:
  - "sbt ++$TRAVIS_SCALA_VERSION test"
  - "sbt ++$TRAVIS_SCALA_VERSION publish-local"

before_script:
  - wget http://downloads.typesafe.com/typesafe-activator/1.3.7/typesafe-activator-1.3.7-minimal.zip
  - unzip -q typesafe-activator-1.3.7-minimal.zip

script:
  - sbt about

notifications:
  email: true