language: scala
scala: 
  - 2.11.6
jdk:
  - oraclejdk8
script:
  - "sbt ++$TRAVIS_SCALA_VERSION test"
  - "sbt ++$TRAVIS_SCALA_VERSION publish-local"

before_script:
  - wget http://downloads.typesafe.com/typesafe-activator/1.3.7/typesafe-activator-1.3.7-minimal.zip
  - unzip -q play-$PLAY_VERSION.zip
script: play-$PLAY_VERSION/play test

notifications:
  email: true